export const emojis = {
	accent: {
		american: '🇺🇸',
		'british-essex': '🇬🇧💅',
		irish: '🇮🇪',
		australian: '🇦🇺',
		british: '🇬🇧',
		'english-swedish': '🇸🇪🇬🇧',
		'american-irish': '🇺🇸🇮🇪',
		'american-southern': '🇺🇸🌵',
		'english-italian': '🇬🇧🇮🇹',
		indian: '🇮🇳',
		african: '🌍',
	},
	description: {
		calm: '🍃',
		'well-rounded': '🟢',
		'war veteran': '🪖',
		'ground reporter': '🎤',
		strong: '💪',
		conversational: '💬',
		sailor: '⚓',
		soft: '🧸',
		casual: '👕',
		raspy: '🗣️',
		emotional: '💖',
		hoarse: '😶‍🌫️',
		shouty: '📢',
		anxious: '😟',
		pleasant: '😊',
		deep: '🌊',
		crisp: '🍎',
		seductive: '💋',
		confident: '😎',
		warm: '🌞',
		'calm ': '🍃',
		excited: '🎉',
		childlish: '🍼', // Note: Presuming "childlish" is a typo for "childish"
		whisper: '🤫',
		'raspy ': '🗣️',
		witch: '🧙‍♀️',
		foreigner: '🌏',
		childish: '🧒',
	},
	age: {
		young: '👶',
		'middle aged': '🧑‍🦳',
		old: '👴',
	},
	gender: {
		female: '♀️',
		male: '♂️',
	},
};
